# Site settings
name: Jiaolong 's Record
email: iwangjiaolong@163.com
author: Jiaolong
url: http://record.jiaolong.space
resume_site: http://record.jiaolong.space
github: https://github.com/luoyan35714/
baseurl: "/LessOrMore"
description: Actually, less is more!
meta_description: Jiaolong;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wang-jiaolong

# Build settings
markdown: kramdown

baidu_analysis: d36219c5c805aadf9278ada56fa7116d

